create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text,
  subject text not null,
  task_id text not null,
  task_number text,
  display_number text,
  section_id text,
  section_title text,
  title text not null default 'Задание',
  solved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, subject, task_id)
);

alter table public.user_progress add column if not exists username text;
alter table public.user_progress add column if not exists section_id text;
alter table public.user_progress add column if not exists section_title text;
alter table public.user_progress enable row level security;

drop policy if exists "Users can read own progress" on public.user_progress;
drop policy if exists "Users can read leaderboard progress" on public.user_progress;
drop policy if exists "Users can insert own progress" on public.user_progress;
drop policy if exists "Users can update own progress" on public.user_progress;
drop policy if exists "Users can delete own progress" on public.user_progress;

create policy "Users can read leaderboard progress"
  on public.user_progress
  for select
  to authenticated
  using (true);

create policy "Users can insert own progress"
  on public.user_progress
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own progress"
  on public.user_progress
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own progress"
  on public.user_progress
  for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.user_progress to authenticated;
grant usage, select on sequence public.user_progress_id_seq to authenticated;

create index if not exists user_progress_subject_idx on public.user_progress(subject);
create index if not exists user_progress_subject_section_idx on public.user_progress(subject, section_id);
